### ISSUE TITLE
Use jest to create a setup file and write a test case for login

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#11]
**Is your feature request related to a problem? Please describe.**
Write unit test case for the login component

**Describe the solution you'd like**
- Add a command yarn test to run all test cases. 
- Write a test case for Login component
- The test should also show the coverage after running

**Comment by ajaman190** [comment]
I would like to work on this issue. Will you please assign it to me?

**Comment by mdshamoon** [comment]
Sure @ajaman190. I have assigned it to you.
