### ISSUE TITLE
Log out on Authentication Error 401: User Access Token Expired

### ISSUE THREAD

**Issue by ajaman190** [glific/mobile#110]
**Log out on Authentication Error 401: User Session Expired**

Currently, the app doesn't properly handle an authentication error 401 when a user's access token expires. No action is taken instead logging the user out and redirecting them to the login screen.

**Approach**

- If an authentication error 401 is detected in contact screen.
- Clear the token stored in the app context and set the session data in the async storage to null.

**Comment by mdshamoon** [comment]
This is completed. Closing
