### ISSUE TITLE
Create a github action file for unit testing with jest 

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#15]
**Is your feature request related to a problem? Please describe.**
For each PR we want to check if nothing is breaking from those changes. To ensure that we will be running the unit test on each Pull request and only merge it if it passes the check

**Describe the solution you'd like**
Create a unit-testing.yml file and check if the action is working on a PR against the main branch

**Describe alternatives you've considered**
Take reference from here: https://github.com/glific/glific-frontend/blob/master/.github/workflows/unit-testing.yml

**Comment by ajaman190** [comment]
I would like to work on this issue. Will you please assign it to me?

**Comment by mdshamoon** [comment]
Sure @ajaman190 I have assigned it to you. I was thinking to upload to Codecov later. 
I will setup the codecov account and add the key.
