### ISSUE TITLE
Add a splash screen with Glific's logo when the app opens

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#16]
**Is your feature request related to a problem? Please describe.**
Add a splash screen with Glific's logo when the app opens

**Describe the solution you'd like**
The logo should be in the center as added in the design file https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=0-1

**Comment by ajaman190** [comment]
I would like to work on this issue. Please assign it to me?
