### ISSUE TITLE
Setup apollo client and make a graphQL api call using the access token we get after login

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#17]
**Is your feature request related to a problem? Please describe.**
To communicate with the backend we have fairly good documented APIs https://api.glific.com . We need to setup Apollo client and use these graphQL API to get data from backend

**Describe the solution you'd like**
- Add apollo client
- Create a config file for apollo that initializes the global settings
- On the chat page use the search query to create a list of first 10 contacts https://api.glific.com/#9a5aac81-0147-4c11-92a2-7b9f1a120ed7

**Comment by ajaman190** [comment]
I would like to work on this issue. Will you please assign it to me?

**Comment by VishalZ123** [comment]
Hey @mdshamoon, I have a little idea of working of graphQL. I would like to take this issue. Will you please assign it to me?

**Comment by mdshamoon** [comment]
Sure @VishalZ123 assigned it to you.

**Comment by mdshamoon** [comment]
Hi @VishalZ123 how's it going?

**Comment by VishalZ123** [comment]
Hello @mdshamoon 
I have setup the apollo client. now reading the glific API docs and figuring out how to make an API call using graphql and axios.
