### ISSUE TITLE
Create a side drawer according to the designs

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#20]
**Is your feature request related to a problem? Please describe.**
Create a side drawer according to the designs

**Describe the solution you'd like**
Only create the structure. We can add functionality later
Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=0-1&t=cvh8szwAja7S8PIA-0

**Screenshot**

<img width="267" alt="image" src="https://github.com/glific/mobile/assets/32592458/5b569e2b-e070-401d-ab67-7fb24c1ab10c">

**Comment by ajaman190** [comment]
@mdshamoon I would like to work on this issue. Please assign it to me?
