### ISSUE TITLE
Update the UI for login screen according to the designs

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#21]
**Is your feature request related to a problem? Please describe.**
Update the UI for login according to the designs

**Describe the solution you'd like**
Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043&t=cvh8szwAja7S8PIA-0

**Comment by ArkaPrabhaChowdhury** [comment]
Hey @mdshamoon. I would like to work on this!

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon Do I have to implement the existing UI in react native or do I have to improve the design in Figma?

**Comment by mdshamoon** [comment]
@ArkaPrabhaChowdhury implement the UI from the design file in React Native app

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon Hey! I am done with the implementation. Whats the next step? Should I open a pull request?

**Comment by mdshamoon** [comment]
@ArkaPrabhaChowdhury yes please create a pull request.
