### ISSUE TITLE
Update the UI for organization URL page according to the designs

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#24]
**Is your feature request related to a problem? Please describe.**
Update the UI for organization URL page according to the designs

**Describe the solution you'd like**
Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=248-4142&t=4dgUT2BddcRhRzRm-0

<img width="239" alt="image" src="https://github.com/glific/mobile/assets/32592458/898de3f6-c0e0-4ca5-a25b-2c21e4d9289a">

**Comment by mdshamoon** [comment]
@Adii-5442 you can work on this issue. Let me know if you have any questions

**Comment by ajaman190** [comment]
@mdshamoon, I am currently researching the push notification issue. In the meantime, could you please assign it to me? I will soon raise the pull request for the push notification implementation.
