### ISSUE TITLE
Add tabs for contacts collection and saved searches on the chat page

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#25]
**Is your feature request related to a problem? Please describe.**
Add tabs for contacts collection and saved searches on the chat page.

**Describe the solution you'd like**
Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=276-3211&t=4dgUT2BddcRhRzRm-0

<img width="280" alt="image" src="https://github.com/glific/mobile/assets/32592458/61fa7589-c785-4d3f-9f5b-dd1421c09f54">

**Comment by mdshamoon** [comment]
@AbhiiNaithani you can pick up this issue. Let me know in case you have any questions

**Comment by AbhiiNaithani** [comment]
@mdshamoon , Can you please share the credentials for login?

**Comment by VishalZ123** [comment]
@AbhiiNaithani you can find it at https://github.com/glific/mobile/issues/3

**Comment by ajaman190** [comment]
@mdshamoon Can I pick up this issue? As while defining the other navigations, I was just left with this part only. So, now I will define them in the correct manner.
