### ISSUE TITLE
Add a contact messages page 

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#26]
**Is your feature request related to a problem? Please describe.**
When we click on a particular contact it will show a list of messages for that contact. 

**Describe the solution you'd like**
We will create a structure for the contact messages. The initial version would have the following features:
- Contact name at the top
- A section for time left
- 4-5 messages

The data will be static for now and we will integrate with the backend at a later stage

<img width="239" alt="image" src="https://github.com/glific/mobile/assets/32592458/d2aff287-53c1-42fc-b128-6c3e18d6c365">

Design file link: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043&t=4dgUT2BddcRhRzRm-0

**Comment by chandra-pro** [comment]
@mdshamoon ok I will start making this page from today itself.

**Comment by chandra-pro** [comment]
What is the server url to proceed further or do i make just contact us page
?

**Comment by chandra-pro** [comment]
@mdshamoon I have done with my job.I'll make a pull request today please review it and let me know if there is any issue.
