### ISSUE TITLE
Add a search bar on the chat page

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#27]
**Is your feature request related to a problem? Please describe.**
Add a search bar on the chat page

**Describe the solution you'd like**
The search bar should be according to the designs: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043&t=4dgUT2BddcRhRzRm-0

<img width="289" alt="image" src="https://github.com/glific/mobile/assets/32592458/75057f40-c9b2-49f2-8521-b3c30a81ac35">

**Comment by ajaman190** [comment]
@mdshamoon, I am currently researching the push notification issue. In the meantime, could you please assign it to me? I will soon raise the pull request for the push notification implementation.
