### ISSUE TITLE
Implement login functionality

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#3]
**Is your feature request related to a problem? Please describe.**
The login page UI is already completed. Now we need to make it functional by making a request to the backend and getting an access token. This token will be used further to make further backend API calls.

**Describe the solution you'd like**
- Once the user clicks on login after typing phone and password make an API call to the backend using this API- https://api.glific.com/#4a9a72a5-01d3-4af4-a7e0-7b50a67c6dac
- This will fetch an access token and it should move to a new page after that. Add a heading "Chat" on the new page

**Additional context**
Backend testing URL: https://api.staging.tides.coloredcow.com/api
Phone: 917834811114
Password: secret1234

Or you can setup the backend in local for ease in testing. Steps for setting up the backend :
https://github.com/glific/glific#readme

**Comment by VishalZ123** [comment]
Hey @mdshamoon 
I would like to work on this issue. Will you please assign it to me?
Thanks

**Comment by ajaman190** [comment]
Hey @mdshamoon, I have opened a pull request related to the issue "Implement login functionality". Could you please review it and provide your feedback? Thank you.

**Comment by mdshamoon** [comment]
Hi @VishalZ123 it seems @ajaman190 already raised a PR for this. Can you work on #5. I will assign it to you.

Also @ajaman190 please check if somebody is already working on an issue and then start working on that. Otherwise it will be just wasted effort for you or the other person.
