### ISSUE TITLE
A logged in user should not be able to go back to login screen

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#38]
**Is your feature request related to a problem? Please describe.**
Right now when we are on the chat screen and press the back button it takes us back to the login. 

**Describe the solution you'd like**
An authenticated user should not be able to go back to the login page unless they click on logout

**Comment by mdshamoon** [comment]
I believe async storage is already a global store. Not sure how adding Redux would help here. If possible can we discuss this over the call and you can show me where its not updating correctly.

**Comment by ajaman190** [comment]
Sure

> I believe async storage is already a global store. Not sure how adding Redux would help here. If possible can we discuss this over the call and you can show me where its not updating correctly.

**Comment by ajaman190** [comment]
![image](https://github.com/glific/mobile/assets/84832565/0a1200d7-2d0c-4b78-817f-d197594d5aa6)

**Comment by ajaman190** [comment]
@mdshamoon  See, this is our main navigator, which allows us to switch our navigation stack from Auth to App. However, when I log in, the token gets stored in async storage but doesn't update locally here.

**Comment by mdshamoon** [comment]
Got it. Since the Async storage is not watched by React the component doesn't re-render on its change. Okay in that case I think just use the React context api for storing the session details once the user logs in and remove from there once the user logs out.
