### ISSUE TITLE
Add a filter list on the chat page when we click on options

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#39]
**Is your feature request related to a problem? Please describe.**
We need to filter the contacts based on the status

**Describe the solution you'd like**
For this we will add a list of all the filters. In this issue just create the structure. We can work on the functionality later.
<img width="330" alt="image" src="https://github.com/glific/mobile/assets/32592458/a76a7496-d29f-413a-8c35-e998d4b4fe46">

Design file https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043

**Comment by ajaman190** [comment]
@mdshamoon I would like to work on this issue. Please assign it to me?
