### ISSUE TITLE
Add a notification icon when on the chat page.

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#40]
**Is your feature request related to a problem? Please describe.**
Add a notification icon when on the chat page.

**Describe the solution you'd like**
When we click on the notification icon it should move us to the notifications page
<img width="256" alt="image" src="https://github.com/glific/mobile/assets/32592458/d6a38a37-1c13-4954-b90b-6a66f17e729f">

Design file
https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043

**Comment by ArkaPrabhaChowdhury** [comment]
@mdshamoon Would love to work on this!
