### ISSUE TITLE
Add wallet balance option in the sidedrawer

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#41]
**Is your feature request related to a problem? Please describe.**
Users need to check the amount of balance left on their bot messaging

**Describe the solution you'd like**
We will show the remaining wallet balance in the sidedrawer.
<img width="244" alt="image" src="https://github.com/glific/mobile/assets/32592458/27b679cf-5dad-49ec-b2fd-b6859710f13c">

API for getting wallet balance

const BSPBALANCE = gql`
  query bspbalance {
    bspbalance
  }
`;

Run this query using Apollo's useQuery hook.

Design file https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043

**Comment by chandra-pro** [comment]
@mdshamoon Please assign me this issue.I'll resolve it by tonight

**Comment by chandra-pro** [comment]
@mdshamoon do we have to use query ''const BSPBALANCE = gqlquery bspbalance { bspbalance };'' for wallet balance?
As it is showing ApolloError Network request failed.

**Comment by ajaman190** [comment]
> @mdshamoon do we have to use query ''const BSPBALANCE = gqlquery bspbalance { bspbalance };'' for wallet balance? As it is showing ApolloError Network request failed.

@chandra-pro Ensure that you have renamed the file from .env.example to .env, as it includes the API_BASE_URL.
