### ISSUE TITLE
Open the contact messages page with contact details and messages

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#48]
**Is your feature request related to a problem? Please describe.**
When we press a contact from the list it should open the messages for the contact along with the contact name on top

**Describe the solution you'd like**

<img width="402" alt="image" src="https://github.com/glific/mobile/assets/32592458/3677ed81-b12a-4b80-ab33-38bf4528652e">

We will use the same search graphql API for getting a particular contacts messages but with different variables
```

{filter: {id: "21"}, contactOpts: {limit: 1}, messageOpts: {limit: 20, offset: 1}}
```

**Comment by ajaman190** [comment]
@mdshamoon I would like to work on this issue. Please assign it to me?
