### ISSUE TITLE
Save the server url in async storage and use it as the API URL rather than the env variable

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#49]
**Is your feature request related to a problem? Please describe.**
Save the server url in async storage and use it as the API URL rather than the env variable

**Comment by chandra-pro** [comment]
It means if we have to use it then just get server url from async storage for usage?
Why we are doing so?

**Comment by chandra-pro** [comment]
Is there any ui to take org url as input from the user?

**Comment by mdshamoon** [comment]
Its the first screen that comes up when you open the app
<img width="331" alt="image" src="https://github.com/glific/mobile/assets/32592458/a58542da-5121-4f1b-bdb0-658c709fb1d6">

**Comment by chandra-pro** [comment]
Okk I'll try to do.

**Comment by chandra-pro** [comment]
I have an idea like we first set org url in async storage as API_URL and replace the other url with get async storage.

**Comment by ajaman190** [comment]
> **Is your feature request related to a problem? Please describe.** Save the server url in async storage and use it as the API URL rather than the env variable

@mdshamoon is there an API available for validating the entered organization URL? It's crucial to perform a check before saving it to the storage to verify if any organization exists with this URL. Otherwise, it will throw a network error in the login page. I have already implemented this functionality using the approach mentioned above. Should I raise a PR for it, or would you like me to make this check first and then raise the PR?

**Comment by mdshamoon** [comment]
> > **Is your feature request related to a problem? Please describe.** Save the server url in async storage and use it as the API URL rather than the env variable
> 
> @mdshamoon is there an API available for validating the entered organization URL? It's crucial to perform a check before saving it to the storage to verify if any organization exists with this URL. Otherwise, it will throw a network error in the login page. I have already implemented this functionality using the approach mentioned above. Should I raise a PR for it, or would you like me to make this check first and then raise the PR?

There's no API available. For now just check if its a valid URL
