### ISSUE TITLE
Store the access token in a store after login

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#5]
**Is your feature request related to a problem? Please describe.**
After login we will get an access token that needs to be stored in some local storage to use in further API calls

**Describe the solution you'd like**
Research and implement various local storage libraries and add one of them in the project to store access token

**Additional context**
Check among these packages https://reactnative.directory/?search=storage

**Comment by mdshamoon** [comment]
@VishalZ123 you can pick up this issue.

**Comment by VishalZ123** [comment]
Hey @mdshamoon 
We can use [Async Storage](https://react-native-async-storage.github.io/async-storage/) for this task. It has 2,657,733 monthly downloads. It is very similar to [Shared Preferences Plugin](https://pub.dev/packages/shared_preferences) for Flutter, except for only being able to store strings.
**Research** - 
- Simple Interface for getting, setting and removing key-value pairs.
- Asynchronous, that means that all its method return promises. Allows you to perform operations without blocking the main thread of your app.
- Persistent, data stored is available even after the app is closed or device is restarted.
- [**Limitation**] Only strings can be stored, other data-types have to be converted into strings first.

But seeing our use case of storing the tokens (which are strings), the limitation is not an issue. We can store the token in the Async Storage, use it for API calls and remove it from the storage at the tome when the user logouts. 

Will you please assign me this issue or should I assign myself?

**Comment by mdshamoon** [comment]
Looks good @VishalZ123. I have assigned it to you.
