### ISSUE TITLE
Add an emoji library to add emojis in a message that we can send 

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#56]
**Is your feature request related to a problem? Please describe.**
Along with text we want to enable the emoji functionality for a user to send the message

**Describe the solution you'd like**
- Check out various emoji libraries and add one of them (or we can use native keyboard emojis).
- When we click on the emoji button it opens up a modal to select an emoji or something like WhatsApp where it opens up from the bottom
- After selecting an emoji it shows up in the input box

<img width="229" alt="image" src="https://github.com/glific/mobile/assets/32592458/1004660e-e58a-4297-acd7-89ff8da737ce">

Check the desgins here: https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043

**Comment by SoumyadiptoPal** [comment]
Please assign me this issue. I want to work on it

**Comment by shashwatm1111** [comment]
Hey , I would like to work upon this issue . Kindly assign me this under C4GT .

**Comment by nishant25062002** [comment]
I am working on this issue @mdshamoon

**Comment by mdshamoon** [comment]
This is completed. Closing
