### ISSUE TITLE
Update the sidedrawer according to the designs

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#60]
**Screenshot**

<img width="285" alt="image" src="https://github.com/glific/mobile/assets/32592458/6e52319b-4a3f-4138-8356-762c9d609ddd">

**Link to design file**

https://www.figma.com/file/SbP0ru8kiB2l334ieX1ESe/Mobile-app?type=design&node-id=195-2043

**Specifics to update**

- Green background at the top. 
- First letter of the organization name as an icon
- Color for logout 
- Check margin and spacing
- Wallet balance is done separately. Please don't add that

**Comment by ajaman190** [comment]
@mdshamoon I would like to work on this issue as i have already worked on this component. So i will fix them in correct format.

**Comment by ajaman190** [comment]
@mdshamoon from which i will get the organization name

**Comment by ANEESH-2003** [comment]
@mdshamoon sir you assigned this issue to me in discord server but as i can see somebody else is also working on it so is it okay for me to continue with this or you can assign me any other issue??

**Comment by ajaman190** [comment]
@mdshamoon can we generate a combined font icon .ttf files for all glific icons, as it is difficult to find same/similar icons, also it reduces project dependencies to some extent.

**Comment by mdshamoon** [comment]
> @mdshamoon sir you assigned this issue to me in discord server but as i can see somebody else is also working on it so is it okay for me to continue with this or you can assign me any other issue??

You can work on this issue https://github.com/glific/mobile/issues/68 @ANEESH-2003

**Comment by mdshamoon** [comment]
> @mdshamoon from which api i will get the organization name

This is the api @ajaman190 
https://api.staging.tides.coloredcow.com/api/v1/session/name

**Comment by mdshamoon** [comment]
> @mdshamoon can we generate a combined font icon .ttf files for all glific icons, as it is difficult to find same/similar icons, also it reduces project dependencies to some extent.

Lets do it at a later stage
