### ISSUE TITLE
Add PR submission guidelines in the Readme

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#66]
**Is your feature request related to a problem? Please describe.**
When a Pull request is raised it should have the following things:

- Pass unit test cases
- The issue link and problem its trying to solve
- Have no deepscan issue
- Fomatting should be correct using prettier

**Comment by mdshamoon** [comment]
@Siva20021 can you check this issue. Since you are new to open source this may help you in understanding what are the things needed while submitting a PR

**Comment by Siva20021** [comment]
Sure I can check that out. So should I add These guidlines to readme file ?

**Comment by mdshamoon** [comment]
> Sure I can check that out. So should I add These guidlines to readme file ?

Yes
