### ISSUE TITLE
Updates in the server URL flow

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#67]
@ajaman190 mostly looks good. Minor things to update:

1. If serverURL is present in storage- Redirect to the login screen.
2. Use the serverUrl in the apollo.ts file as well
3. The backend url format is  https://api.{URL}/api
  For ex: If my frontend URL is staging.tides.coloredcow.com then the server URL will become 
  https://api.staging.tides.coloredcow.com/api. The User will only type the frontend URL and 
  the rest we will manage in the code
  
  
You can take this up in a separate branch as there are a lot of file changes here

_Originally posted by @mdshamoon in https://github.com/glific/mobile/pull/61#pullrequestreview-1447402142_

**Comment by VishalZ123** [comment]
Hey @mdshamoon 
I would like to work on the issue. Please assign it to me.
