### ISSUE TITLE
Create contact search functionality

### ISSUE THREAD

**Issue by mdshamoon** [glific/mobile#72]
**Is your feature request related to a problem? Please describe.**
When we type something in the search box it should return the search results and display in the contact list area

**Describe the solution you'd like**
For this we will use the same search query but with the filter variable included:

```
const variables = {
  filter: { term: "Search value"},
  messageOpts: { limit: 3, offset: 0 },
  contactOpts: { limit: 10, offset: 0 },
};
```

**Comment by chandra-pro** [comment]
@mdshamoon Ok I will work on this.
Is the search value input given by user?
Is there any other info required ?

**Comment by mdshamoon** [comment]
Yes @chandra-pro it will be given by user in this search box
<img width="404" alt="image" src="https://github.com/glific/mobile/assets/32592458/2685c837-853e-4bf6-9ac2-d6a569880a31">

**Comment by chandra-pro** [comment]
Ok, thanks.

**Comment by mdshamoon** [comment]
This is completed. Closing
