### ISSUE TITLE
Implement dedicated video player

### ISSUE THREAD

**Issue by ajaman190** [glific/mobile#98]
**Is your feature request related to a problem? Please describe.**
Create a dedicated video player.

**Describe the solution you'd like**
- On press video message, the video player should open in full-screen mode.
- Users should be able to control the video using video controller.
- The video player should have an option to return back to the message thread view, and have sender information.

**Comment by ajaman190** [comment]
@mdshamoon This is also done.

**Comment by mdshamoon** [comment]
This is completed. Closing.
